name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use macos-latest or windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Specify your Flutter version

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run Flutter analyze
        run: |
          flutter analyze

      - name: Run Flutter test
        run: |
          flutter test

      - name: Build APK (release)
        run: |
          flutter build apk --release  # Build the APK in release mode

      - name: Upload APK as build artifact
        uses: actions/upload-artifact@v2  # Use v2 for upload-artifact
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Path to the APK file
