name: Build Flutter APK for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for this workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'  # Make sure to use a version that supports Dart 3.7.2

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
