name: Build Flutter APK for Android

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  build:
    runs-on: windows-latest  # Use Windows since you're developing on Windows
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter (latest stable)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Use the latest stable Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk
